### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by shashikiran797** [deej81/ngx-croppie-example#1]
![image](https://user-images.githubusercontent.com/16119169/37204196-079f3cea-23b6-11e8-8b96-3fb326d2450b.png)

**Comment by deej81** [comment]
thanks for reporting this. The latest version of croppie has an issue with it's module structure.

https://github.com/deej81/ngx-croppie/issues/5

I'll tie the example app to an earlier croppie version for now
